# Project information
site_name: Checkout
site_description: Technical documentation for the implementation of Evertec's Checkout solution
site_author: Eliezer Ferrá
site_url: https://elio-developer.github.io/checkout/

# Copyright
copyright: 'Copyright &copy; 2019 Evertec Inc., changes by Eliezer Ferrá'

theme:
    name: 'material'
    palette:
        primary: 'grey'
        accent: 'orange'
    font:
        text: 'Lato'
    logo: 'images/logo.svg'
    favicon: 'images/favicon.png'

markdown_extensions:
    - markdown.extensions.admonition
    - footnotes
    - codehilite

nav:
    - Home: index.md
    - Payment Services:
        - Web Checkout: webCheckout.md
        - Process Credit: credit.md
        - Process ACH: ach.md
        - Process Wallet: wallet.md
        - Transaction Search: trxSearch.md
    - Other Services:
        - ACH Services: achServices.md
        - Daily Closing Process: closing.md
    - Testing:
        - Sandbox Credentials: testing.md
        - Postman Collection: postman.md
    - API Reference:
        - Samples:
            - Web Checkout: webCheckout_sample.md
            - Process Credit: credit_sample.md
            - Process ACH: ach_sample.md
            - Process Wallet: wallet_sample.md
            - Transaction Search: trxSearch_sample.md
        - Response Codes: 
            - General: responseCodes.md
            - Process ACH: responseCodesACH.md
        - Payment Methods: paymentMethod.md